source "https://rubygems.org"
ruby "3.2.0"
gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.7"
gem "jsonapi-serializer"
gem "kaminari"
gem "rack-cors"
gem "aws-sdk-s3"
gem "fhir_models"
gem "pundit"
gem "blueprinter"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-rails"
end

group :development do
  gem "listen"
end
